version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    cooldown:
      default-days: 7
    # Prefix commit messages with "deps" to include dependency updates in patch releases
    commit-message:
      prefix: deps
    # Group codeql-action updates together to avoid multiple pull requests for the same update. Important that all CodeQL updates are taken simultaneously to avoid version mismatches between the init and analyze actions.
    # Different versions of the init and analyze actions can cause errors in the CodeQL analysis.
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
    cooldown:
      default-days: 7
    commit-message:
      prefix: build
    groups:
      uv:
        patterns: ["*"]
