extends: ["@commitlint/config-conventional"]
rules:
  scope-enum:
    - 2
    - always
    - - azure-function
      - azure-webapp
      - commitlint
      - databricks-bundle
      - databricks-repos
      - docker-acr
      - docker
      - dotnet
      - github-pages
      - mkdocs
      - python-package
      - python
      - release-please
      - semantic-release
      - terraform
      - trivy-config-codeql
      - zizmor-codeql
