# Restore, build and publish .NET Core application.

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: The version of .NET to install.
        type: string
        required: true

      configuration:
        description: Defines the build configuration.
        type: string
        required: false
        default: Release

      runtime:
        description: Which runtime to publish the application for.
        type: string
        required: false
        default: ""

      self_contained:
        description: Publish the .NET runtime with your application so the runtime doesn't need to be installed on the target machine?
        type: boolean
        required: false
        default: false

      artifact_name:
        description: The name of the build artifact to upload.
        type: string
        required: false
        default: dotnet-app

    outputs:
      artifact_name:
        description: The name of the build artifact that was uploaded.
        value: ${{ inputs.artifact_name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: ${{ inputs.configuration }}
      RUNTIME: ${{ inputs.runtime }}
      SELF_CONTAINED: ${{ inputs.self_contained }}
      OUTPUT: dotnet-app

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Dotnet restore
        run: dotnet restore

      - name: Dotnet build
        run: dotnet build --configuration "$CONFIGURATION" --runtime "$RUNTIME" --no-restore

      - name: Dotnet publish
        run: dotnet publish --runtime "$RUNTIME" --self-contained "$SELF_CONTAINED" --output "$OUTPUT" --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ env.OUTPUT }}
