name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload SARIF file
      contents: read # Required in private repositories
      actions: read # Required in private repositories
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e

      - name: Run zizmor 🌈
        run: uvx zizmor --format=sarif . > results.sarif
        env:
          # Run zizmor in offline mode. Online mode currently struggles due to
          # inconsistencies in the GitHub API, resulting in zizmor being unable
          # to fetch some remote repositories.
          # Ref: https://docs.zizmor.sh/usage/#operating-modes
          ZIZMOR_OFFLINE: "true"
          # To check if online mode has been fixed in the latest version of
          # zizmor, replace the ZIZMOR_OFFLINE environment variable with
          # GH_TOKEN to enable online mode, then trigger this workflow.

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@3599b3baa15b485a2e49ef411a7a4bb2452e7f93
        with:
          sarif_file: results.sarif
          category: zizmor
