on:
  workflow_call:
    inputs:
      title:
        description: The title of the issue.
        type: string
        required: true

      body:
        description: The body of the issue.
        type: string
        required: false
        default: ""

      body_file:
        description: The path of a file containing the body of the issue, e.g. an Issue template.
        type: string
        required: false
        default: ""

      assignee:
        description: A comma-separated string of GitHub users to be assigned to the issue, e.g. "user1,user2".
        type: string
        required: false
        default: ""

jobs:
  gh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: inputs.body_file != ''
        uses: actions/checkout@v3

      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: ${{ inputs.title }}
          BODY: ${{ inputs.body }}
          BODY_FILE: ${{ inputs.body_file }}
          ASSIGNEE: ${{ inputs.assignee }}
        run: gh issue create --repo "GITHUB_REPOSITORY" --title "$TITLE" --body "$BODY" --body-file "$BODY_FILE" --assignee "$ASSIGNEE"
