name: ♻ github-pages

on:
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the artifact containing the site to deploy.
        type: string
        required: true

jobs:
  github-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest

    concurrency:
      group: pages
      cancel-in-progress: false

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - name: Unzip
        env:
          ZIP_FILE: ${{ inputs.artifact_name }}.zip
        run: |
          unzip "$ZIP_FILE"
          rm "$ZIP_FILE"

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
