name: ♻ github-pages

on:
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the artifact containing the site to deploy. Must contain a tarball.
        type: string
        required: true

jobs:
  github-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest

    concurrency:
      group: pages
      cancel-in-progress: false

    permissions:
      # Set permissions required to deploy to GitHub Pages.
      pages: write
      id-token: write

    environment:
      # Setting a different environment name is possible, but not recommended by GitHub.
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ inputs.artifact_name }}
