name: ♻ github-pages

on:
  workflow_call:
    inputs:
      runs_on:
        description: The label of the runner (GitHub- or self-hosted) to run this workflow on. Defaults to 'ubuntu-22.04'.
        type: string
        required: false
        default: ubuntu-22.04
      artifact_name:
        description: The name of the artifact containing the site to deploy. Must contain a tarball.
        type: string
        required: true

permissions: {}

jobs:
  github-pages:
    name: GitHub Pages
    runs-on: ${{ inputs.runs_on}}

    concurrency:
      group: pages
      cancel-in-progress: false

    permissions:
      pages: write # Required to deploy to GitHub Pages
      id-token: write # Required to verify that GitHub Pages deployment originates from appropriate source

    environment:
      # Setting a different environment name is possible, but not recommended by GitHub.
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
        with:
          artifact_name: ${{ inputs.artifact_name }}
