name: 🧹 Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint-codebase:
    name: Lint codebase
    uses: ./.github/workflows/super-linter.yml
    with:
      filter_regex_exclude: docs/workflows/.*

  lint-pr:
    name: Lint PR
    uses: ./.github/workflows/commitlint.yml
    with:
      message: ${{ github.event.pull_request.title }}
