name: Lint Codebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-actions:
    name: Lint actions
    uses: ./.github/workflows/zizmor-codeql.yml
    permissions:
      contents: read
      security-events: write
      actions: read
