name: Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  lint-codebase:
    name: Lint codebase
    uses: ./.github/workflows/super-linter.yml
    permissions:
      contents: read
      statuses: write
    with:
      filter_regex_exclude: (.*CHANGELOG\.md$|docs/workflows/.*)

  lint-pr:
    name: Lint PR
    uses: ./.github/workflows/commitlint.yml
    with:
      message: ${{ github.event.pull_request.title }}
