name: 🧹 Lint codebase

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/super-linter.yml
    with:
      filter_regex_exclude: docs/workflows/.*
