name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions: {}

jobs:
  lint-actions:
    name: Lint Actions
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: ./.github/workflows/zizmor-codeql.yml

  lint-pr:
    name: Lint PR
    permissions:
      contents: read
    uses: ./.github/workflows/commitlint.yml
    with:
      message: ${{ github.event.pull_request.title }}
