name: Publish Docs

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions: {}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/mkdocs.yml
    with:
      requirements: requirements-docs.txt
      strict_mode: true
      upload_artifact: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: read

  deploy:
    name: Deploy
    needs: build
    if: needs.build.outputs.artifact_uploaded == 'true'
    uses: ./.github/workflows/github-pages.yml
    with:
      artifact_name: ${{ needs.build.outputs.artifact_name }}
    permissions:
      pages: write
      id-token: write
