# Lint your Python project using the Ruff Linter.
# Ref: https://docs.astral.sh/ruff/linter/

name: ♻ python-lint

on:
  workflow_call:
    inputs:
      runs_on:
        description: The label of the runner (GitHub- or self-hosted) to run this workflow on. Defaults to `ubuntu-24.04`.
        type: string
        required: false
        default: ubuntu-24.04

permissions: {}

jobs:
  ruff:
    name: Ruff
    runs-on: ${{ inputs.runs_on }}
    permissions:
      contents: read # Required to checkout the repository.
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff check --output-format=github .
