name: ♻ release-please

on:
  workflow_call:
    inputs:
      runs_on:
        description: The label of the runner (GitHub- or self-hosted) to run this workflow on. Defaults to `ubuntu-24.04`.
        type: string
        required: false
        default: ubuntu-24.04

      release_type:
        description: The type of release to create (see [supported release types](https://github.com/googleapis/release-please/blob/main/README.md#strategy-language-types-supported)). Defaults to `simple`.
        type: string
        required: false
        default: simple

    outputs:
      release_created:
        description: "`true` if a release was created, else `false`."
        value: ${{ jobs.release-please.outputs.release_created }}

      tag_name:
        description: The tag name that was created for the release, empty if a release was not created.
        value: ${{ jobs.release-please.outputs.tag_name }}

permissions: {}

jobs:
  release-please:
    name: Release Please
    runs-on: ${{ inputs.runs_on }}
    permissions:
      contents: write # Required to update changelog file
      issues: write # Required to label issues
      pull-requests: write # Required to create release PRs
    steps:
      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c
        with:
          release-type: ${{ inputs.release_type }}

    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
