name: Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    name: Release
    permissions:
      contents: write # Required to update changelog file
      issues: write # Required to label issues
      pull-requests: write # Required to create release PRs
    uses: ./.github/workflows/release-please-manifest.yml

  lock:
    name: Update lockfile
    needs: release
    if: needs.release.outputs.prs_created == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push commit to release PR
    strategy:
      matrix:
        pr_branch_name: ${{ fromJSON(needs.release.outputs.pr_branch_names) }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ matrix.pr_branch_name }}
          persist-credentials: true # Required to push commit to release PR

      - name: Setup uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0

      - name: Update lockfile
        run: uv lock

      - name: Commit lockfile
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add uv.lock
          git commit -m "Update lockfile"
          git push
