name: ♻ release-please

on:
  workflow_call:
    inputs:
      runs_on:
        description: The label of the runner (GitHub- or self-hosted) to run this workflow on. Defaults to `ubuntu-24.04`.
        type: string
        required: false
        default: ubuntu-24.04

      release_type:
        description: The type of release to create (see [supported release types](https://github.com/googleapis/release-please/blob/main/README.md#strategy-language-types-supported)). Defaults to `simple`.
        type: string
        required: false
        default: simple

    outputs:
      releases_created:
        description: Value is `true` if any release was created, else `false`.
        value: ${{ jobs.release-please.outputs.releases_created }}

      paths_released:
        description: Value is a JSON array of paths that had releases created, `[]` if nothing was released.
        value: ${{ jobs.release-please.outputs.paths_released }}

      release_created:
        description: Value is `true` if a release was created for the root package (path is `.`), else `false`.
        value: ${{ jobs.release-please.outputs.release_created }}

      tag_name:
        description: Value is the tag name that was created for the root package, empty if a release was not created for the root package.
        value: ${{ jobs.release-please.outputs.tag_name }}

      path_tag_names:
        description: Value is a JSON object of key-value pairs, where the key is a path that had a release created, and the value is the tag name that was created for that release.
        value: ${{ jobs.release-please.outputs.path_tag_names }}

permissions: {}

jobs:
  release-please:
    name: Release Please
    runs-on: ${{ inputs.runs_on }}
    permissions:
      contents: write # Required to update changelog file
      pull-requests: write # Required to create release PRs
    steps:
      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c
        with:
          release-type: ${{ inputs.release_type }}
      
        # The Release Please action dynamically defines outputs for each path
        # that had a release created. Dynamically defining outputs for a job is
        # not supported, so we have to convert the entire Release Please action
        # outputs object to a JSON object, then use jq to construct static JSON
        # objects containing the specific outputs that we need.
        # Ref: https://github.com/googleapis/release-please-action/blob/c2a5a2bd6a758a0937f1ddb1e8950609867ed15c/README.md#path-outputs
      - name: Set path outputs
        id: set-path-outputs
        env:
          OUTPUTS_JSON: ${{ toJSON(steps.release-please.outputs) }}
        run: |
          path_tag_names=$(echo "$OUTPUTS_JSON" | jq 'with_entries(select(.key | endswith("--tag_name")) | .key |= rtrimstr("--tag_name"))')
          echo "path_tag_names=$path_tag_names" >> "$GITHUB_OUTPUT"

    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      paths_released: ${{ steps.release-please.outputs.paths_released }}
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
      path_tag_names: ${{ steps.set-path-outputs.outputs.path_tag_names }}
