# TODO(@hknutsen): Write a description.

on:
  workflow_call:
    inputs:
      environment:
        description: The environment that the job references.
        required: true
        type: string

      client_id:
        description: The client ID of the Azure Service Principal used for authenticating to Azure.
        required: true
        type: string

      tenant_id:
        description: The tenant ID of the Azure Service Principal used for authenticating to Azure.
        required: true
        type: string

      subscription_id:
        description: The ID of the Azure Subscription to provision the Azure resources for.
        required: true
        type: string

      server_name:
        description: ""
        required: true
        type: string

      resource_group_name:
        description: ""
        required: true
        type: string

      vault_name:
        description: ""
        required: true
        type: string

      secret_name:
        description: ""
        required: true
        type: string

    secrets:
      client_secret:
        description: The client secret of the Azure Service Principal used for authenticating to Azure.
        required: true

jobs:
  admin-password:
    name: Admin password
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Run PowerShell script
        uses: azure/powershell@v1
        with:
          azPSVersion: "5.9.0"
          inlineScript: |
            $ClientId = '${{ inputs.client_id }}'
            $ClientSecret = ConvertTo-SecureString '${{ secrets.client_secret }}' -AsPlainText -Force
            $TenantId = '${{ inputs.tenant_id}}'
            $SubscriptionId = '${{ inputs.subscription_id }}'
            $ServerName = '${{ inputs.server_name }}'
            $ResourceGroupName = '${{ inputs.resource_group_name }}'
            $VaultName = '${{ inputs.vault_name }}'
            $SecretName = '${{ inputs.secret_name }}'

            $Credential = New-Object System.Management.Automation.PSCredential($ClientId, $ClientSecret)
            $null = Connect-AzAccount -ServicePrincipal -TenantId $TenantId -Credential $Credential
            Set-AzContext -SubscriptionId $SubscriptionId

            Write-Host 'Generating random password.'
            $Length = 128
            $Lower = 'a'..'z'
            $Upper = 'A'..'Z'
            $Digit = '0'..'9'
            $Symbol = @('!', '$', '#', '%')
            $Characters = $Lower + $Upper + $Digit + $Symbol
            do {
              $Password = ''
              for ($i = 0; $i -lt $Length; $i++) {
                $Password += $Characters | Get-Random
              }
              $HasLower = $Password -cmatch '[a-z]'
              $HasUpper = $Password -cmatch '[A-Z]'
              $HasDigit = $Password -match '[0-9]'
            }
            until ($HasLower -and $HasUpper -and $HasDigit)
            $Password = $Password | ConvertTo-SecureString -AsPlainText -Force

            Write-Host "Updating SQL server '$ServerName' admin password."
            $null = Set-AzSqlServer -ServerName $ServerName -ResourceGroupName $ResourceGroupName -SqlAdministratorPassword $Password

            $KeyVaultFirewall = (Get-AzKeyVault -VaultName $VaultName).NetworkAcls
            $KeyVaultFirewallRules = $KeyVaultFirewall.IpAddressRanges
            $KeyVaultFirewallEnabled = $KeyVaultFirewall.DefaultAction -eq 'Deny'
            Write-Host "Key vault '$VaultName' firewall enabled: $KeyVaultFirewallEnabled."

            try {
              if ($KeyVaultFirewallEnabled) {
                $PublicIp = "$((Invoke-WebRequest -uri 'http://ifconfig.me/ip').Content)/32"
                $KeyVaultFirewallContainsIp = $KeyVaultFirewallRules -contains $PublicIp
                Write-Host "Key vault firewall rules contain public IP '$PublicIp': $KeyVaultFirewallContainsIp."

                if (!$KeyVaultFirewallContainsIp) {
                  Write-Host 'Adding public IP to key vault firewall rules.'
                  $null = Update-AzKeyVaultNetworkRuleSet -VaultName $VaultName -IpAddressRange ($KeyVaultFirewallRules + $PublicIp)
                }
              }

              Write-Host "Updating key vault secret '$SecretName' value."
              $SecretExpires = (Get-Date).AddYears(1)
              $Secret = Set-AzKeyVaultSecret -Name $SecretName -VaultName $VaultName -SecretValue $Password -ContentType 'password' -Expires $SecretExpires
              $Secret

              Write-Host "Disabling old key vault secret versions."
              $SecretVersions = (Get-AzKeyVaultSecret -Name $SecretName -VaultName $VaultName -IncludeVersions | Where-Object { $_.Enabled }).Version
              foreach ($v in $SecretVersions) {
                if ($v -ne $Secret.Version) {
                  $null = Update-AzKeyVaultSecret -Name $SecretName -VaultName $VaultName -Version $v -Enable $false
                }
              }
            }
            catch {
              Write-Error $_.Exception
            }
            finally {
              if (!$KeyVaultFirewallContainsIp) {
                Write-Host 'Restoring key vault firewall rules.'
                $null = Update-AzKeyVaultNetworkRuleSet -VaultName $VaultName -IpAddressRange $KeyVaultFirewallRules
              }
            }

            Disconnect-AzAccount
